### ISSUE TITLE
pom.xml当中的依赖是不是应该是angel-ps-mllib?

### ISSUE THREAD

**Issue by mattxia** [Angel-ML/serving#1]
<dependency>
            <groupId>com.tencent.angel</groupId>
            <artifactId>angel-ps-mllib</artifactId>
            <version>2.0.0</version>

**Comment by mattxia** [comment]
原来写的是,麻烦更新到最新哈...难道没有人用么？
<dependency>
            <groupId>com.tencent.angel</groupId>
            <artifactId>angel-mlcore</artifactId>
            <version>2.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.protobuf</groupId>
                    <artifactId>protobuf-java</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by wangcaihua** [comment]
this version of "Serving" is not relase now, we will release a corresponding Angel to suport "Serving" to maker sure working.

**Comment by wangcaihua** [comment]
if you want to try "Serving" now, you can pull the latest code of Angel from github: https://github.com/Angel-ML/angel

and than switch to the "serving" branch, and compile and install to the local maven repository

next pull the "serving" code, select the "develop" branch, compile 

enjoy!
